project:
  type: book
  output-dir: _book
  execute-dir: project
  preview: 
    port: 4200

book:
  output-file: "bachelor-thesis"
  title: "Are «bioplastics» a solution to plastic pollution in the ocean?"
  subtitle: |
    Laboratory testing of Ecovio\textregistered\ compostable plastic
    potential biodegradation in lake and marine benthic environments
  author: "Vera Gómez-Limón Gallardo"
  date: last-modified
  chapters:
    - index.qmd
    - 1-intro.qmd
    - 2-methods.qmd
    - 3-results.qmd
    - 4-discussion.qmd
    - 5-conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    geometry:
      - left=3.0cm
      - right=3.0cm
      - top=3.5cm
      - bottom=3.5cm
    fig-pos: H
    number-sections: true
    colorlinks: true
    template-partials:
      - "latex/before-body.tex"
      - "latex/titlepage.tex" 
      - "latex/academic-info.tex"
    include-in-header: 
      - "latex/in-header.tex"

execute: 
  echo: false

